sudo: required

language: cpp

services:
  - docker

before_install:
  - docker pull kitech/archlinux
  - docker run -d --name=ruby-jit-qt-dkbox kitech/archlinux /bin/sh -c "sleep 1234567890"
  - docker ps -a 

install:
  - docker exec ruby-jit-qt-dkbox /bin/sh -c "pacman -Suyy --noconfirm"
  - docker exec ruby-jit-qt-dkbox /bin/sh -c "pacman -S --noconfirm clang make git cmake qt5"
  - docker exec ruby-jit-qt-dkbox /bin/sh -c "pwd; ls"
  - docker exec ruby-jit-qt-dkbox /bin/sh -c "cd /; git clone https://github.com/kitech/ruby-jit-qt.git"
  - docker exec ruby-jit-qt-dkbox /bin/sh -c "pwd; ls"

script:
  - docker exec ruby-jit-qt-dkbox /bin/sh -c "cd /ruby-jit-qt; cmake .; make"

notifications:
  email: false

