sudo: required

language: cpp

services:
  - docker

before_install:
  - docker pull kitech/archlinux
  - docker run -d kitech/archlinux --name=ruby-jit-qt-dkbox /bin/sh -c "sleep 1234567890"
  - docker ps -a 

script:
  - docker exec ruby-jit-qt-dkbox "pacman -Suyy --noconfirm"

notifications:
  email: false

